### ISSUE TITLE
Tuning question?

### ISSUE THREAD

**Issue by kenpchess** [knguy22/Blocky-Chess-Engine#240]
Hello! Looks like a nice engine. Can you provide some information and example commands on how your "extract" utility works? Thanks in advance! - Ken

**Comment by knguy22** [comment]
Thanks for the kind words!

Essentially, `extract` is used to convert Blocky's self-play games (PGNs from cutechess) into a `fen; [score]` format that's accepted by [this](https://github.com/GediminasMasaitis/texel-tuner) evaluation tuner. This and similar formats are used to score many positions in order to tune HCEs, like the Ethereal, Zurichess, or lichess-big3 datasets. 

There are probably open source alternatives that do this faster and more flexibly, but I couldn't be bothered to find them and just wrote my own. This also gives me the opportunity to filter positions based on Blocky's search or rescore positions based on Blocky's eval in the future, but that's not implemented yet. I've just hardcoded a constant value `MOD_FENS` that rejects 3/4 positions randomly, and I only use win/draw/loss to score positions.

After compiling `extract` and running it, it searches for a `sources.csv` file in the same directory, and that file contains the pgn files that are to be processed. `sources.csv` should be formatted as follows:

```
PATH_TO_PGN_1,PATH_TO_OUTPUT_1
PATH_TO_PGN_2,PATH_TO_OUTPUT_2
...
```

Assuming that everything else is set up, simply running `./extract` would extract the pgns into the desired datasets. There isn't much for flexibility or changing behavior right now.
